apiVersion: v2
appVersion: "v1.1.0"
description: A Helm chart for Argo Rollouts
name: argo-rollouts
version: 2.2.1
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexmt
  - name: dthomson25
  - name: jessesuen
annotations:
  artifacthub.io/changes: |
    - "[Changed]: updated rollouts version to 1.1.0 and updated CRDs to reflect the version bump"
    - "[Added]: Ability to set the type of Service on the dashboard Service.
